# Generated by Django 5.2.9 on 2025-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
